### ISSUE TITLE
Sections

### ISSUE THREAD

**Issue by Weilandator** [weilandia/soup_tools#11]
Can we have a section for "Today's" TRs and Archived TRs?  Ultimately we will have multiple TRs for the day but having things automatically move to an ARchive section would be helpful. THoughts?

**Comment by weilandia** [comment]
Sounds good.  What's logic for automatically archiving? tr created_at date past?

**Comment by Weilandator** [comment]
Basically on the day… At midnight all TRs from that day move and the Current is blank…
