### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by Weilandator** [weilandia/soup_tools#5]
We need to delete any duplicate based on Price -  The higher price needs to STAY.

Lower price needs to be deleted.

**Comment by weilandia** [comment]
@Weilandator duplicates shouldn't be being created.  Are you seeing that they are?

**Comment by Weilandator** [comment]
No - but did you see the additional notes?

Mike

On Mar 3, 2017, at 20:19, Nick Weiland <notifications@github.com<mailto:notifications@github.com>> wrote:


@Weilandator<https://github.com/Weilandator> duplicates shouldn't be being created. Are you seeing that they are?

**Comment by weilandia** [comment]
Additional notes in this ticket or somewhere else?

**Comment by Weilandator** [comment]
Should be in the ticket

Mike

On Mar 3, 2017, at 20:58, Nick Weiland <notifications@github.com<mailto:notifications@github.com>> wrote:


Additional notes in this ticket or somewhere else?

**Comment by Weilandator** [comment]
It is the SEWP Price column and the Lower price needs to be overwritten with the higher price.
