### ISSUE TITLE
WordPad versus Notepad

### ISSUE THREAD

**Issue by Weilandator** [weilandia/soup_tools#7]
Weird one for you...  So we we download the txt file from the app and open it in notepad (our normal MO) the formatting is all screwed.  However, when we open it in wordpad first save the txt file and then open it in notepad, the formatting is fine.

This isn't a major issue but thought I'd ask incase it was a simple / quick fix... We can adjust how we do things if you're not sure.

**Comment by weilandia** [comment]
hmm it's a plain txt file, so there is literally nothing changing the format on my end.  Notepad must be doing weird formatting on the fly.

**Comment by weilandia** [comment]
I would move the company to use a better default editor if you have to deal with txt files.

http://www.pprune.org/computer-internet-issues-troubleshooting/439393-text-files-not-formatted-properly-notepad.html
