### ISSUE TITLE
Delete Button for TR Templates

### ISSUE THREAD

**Issue by Weilandator** [weilandia/soup_tools#9]
The delete button doesn't delete the record

**Comment by Weilandator** [comment]
I still can't delete a line...

**Comment by weilandia** [comment]
It won't delete templates that are already attached to trs.  I'll think about how we want to manage this, but for now you can move any tr off the templates you want to delete then you can delete the template

**Comment by Weilandator** [comment]
For now you can actually wipe all TRs if that is easier… Template changes will be vary infrequent
